version: '3.8'

services:
  flamenco-manager:
    build:
      context: .
      dockerfile: Dockerfile.manager
    container_name: flamenco-manager
    ports:
      - "50129:8080"
    environment:
      - FLAMENCO_MANAGER_NAME=Flamenco Manager
      - FLAMENCO_DATABASE=flamenco-manager.sqlite
      - FLAMENCO_LISTEN=:8080
      - FLAMENCO_AUTODISCOVERABLE=true
      - FLAMENCO_LOCAL_STORAGE_PATH=./flamenco-manager-storage
      - FLAMENCO_SHARED_STORAGE_PATH=/mnt/shared/flamenco
      - FLAMENCO_SHAMAN_ENABLED=true
      - FLAMENCO_TASK_TIMEOUT=10m0s
      - FLAMENCO_WORKER_TIMEOUT=1m0s
      - FLAMENCO_BLOCKLIST_THRESHOLD=3
      - FLAMENCO_TASK_FAIL_AFTER_SOFTFAIL_COUNT=3
    volumes:
      - ./shared-storage:/mnt/shared/flamenco
      - flamenco-manager-data:/flamenco
    networks:
      - flamenco-network
    restart: unless-stopped

  blender-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: blender-worker
    environment:
      - MANAGER_URL=http://flamenco-manager:8080
      - FLAMENCO_WORKER_NAME=BlenderProc Worker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility
      # Headless rendering configuration
      - DISPLAY=:99
      - XDG_RUNTIME_DIR=/tmp
      - LIBGL_ALWAYS_SOFTWARE=1
      - XVFB_WHD=1920x1080x24
      # Force GPU rendering
      - CYCLES_DEVICE=CUDA
      - BLENDER_GPU_COMPUTE=1
      - CUDA_VISIBLE_DEVICES=0
      - BLENDER_USER_CONFIG=/tmp/blender_config
    volumes:
      - ./shared-storage:/mnt/shared/flamenco
      # Mount current directory as /data as recommended by BlenderProc
      - .:/data
    networks:
      - flamenco-network
    depends_on:
      - flamenco-manager
    restart: unless-stopped
    # GPU support using LinuxServer recommended configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [compute,video,graphics,utility]
    # Scale workers as needed
    scale: 1

networks:
  flamenco-network:
    driver: bridge

volumes:
  shared-storage:
  flamenco-manager-data: